views/dashboard.py
# -*- coding:utf-8 -*-


from flask.blueprints import Blueprint
from flask import render_template, request, jsonify
from echo_telegram_base import try_except, dao
from app_logger import logger
from flask_login import login_required, current_user
import json
from datetime import timedelta


dashboard_view = Blueprint("dashboard_view", __name__)


@dashboard_view.route('/dashboard',  methods=['POST', 'GET'])
@try_except
@login_required
def dashboard():
    # 현재 사용자의 이벤트들을 select 해서 가져온 다음 넘겨줌
    cursor = dao.get_conn().cursor()
    cursor.execute('''
                    select users.user_id ,rank, status, name, seat_location, users.id, category, place, 
                    subject, start_time, attendants, channel_name, iscomplete
                    from users left join channels
                    on users.channel_id = channels.id
                    left join events 
                    on users.id = events.user_id 
                    and iscomplete = 0
                    where users.channel_id = %s;
                    ''', [current_user.channel])
    events = [dict((cursor.description[idx][0], value)
                  for idx, value in enumerate(row)) for row in cursor.fetchall()]

    for event in events:
        if event['attendants'] is not None:

            attendants_text = event['attendants'].replace('\r\n', '||')
            event['attendants'] = attendants_text

    # if request.get == reload 면 json으로 response 보내기
    if request.method == 'POST':
        # events 돌면서 time 들어가는 속성들 문자열로 바꿔주기

        for event in events:
            for key, value in event.items():
                if type(value) is timedelta:
                    event[key] = unicode(str(value), 'utf-8')
        return jsonify(result=events)

    return render_template('dashboard.html', events=events)

views/main.py
#-*- coding:utf-8 -*-
from flask.templating import render_template
from flask.blueprints import Blueprint

main_view = Blueprint("main_view", __name__)


@main_view.route("/")
def index():
    return render_template("index.html")

templates/dashboard.html
{% extends "layout.html" %}

{% block title %}dash_board{% endblock %}

{% block body %}
<style>
    .wrap{
        display: flex;
    }
    .container{
        background: rgb(240, 241, 248);
        height: 94vh;
    }
    .menu_body{
        flex: auto;
    }
    .add_wrap{
        text-align: center;
        margin: 0 auto;
        padding-top: 10%;
    }
    .add_wrap > button{
        width: 150px;
        font-size: 140px;
    }
    .add_wrap > div{
        font-size: 30px;
        font-weight: 800;
    }
    #seat-grid{
    }
    .row{
        display: flex;
    }
    .row > .col{
        height: 15.3vh;
        flex: 1;
        position: relative;
        color: #fff;
        font-weight: bold;
        font-size: 20px;
        border: solid 1.5px #fff;
    }
    .row > .col:hover{
        cursor: pointer;
        background: rgb(40,160,294);
        opacity: 0.3;
    }
    .view-mode{

    }
    .place-box{
        background: #1cc88a;
    }
    .empty-box{
        background: #f6c23e;
    }
    .logout-box{
        background: #858796
    }
    .name-wrap{
        display: inline-block;
        text-align: right;
        width: 100%;
        position: absolute;
        bottom: 10px
    }
    .user-name, .user-rank{
        display: inline-block;
    }
    .info-content, .info-tag{
        display: inline-block;
    }
    .info-tag{
        width: 70px;
        color: rgb(40,160,294)
    }
    .info-content{
        font-weight: 900;
    }
</style>
<script>
    eventsArray = new Array();

    $(function(){
        function update_user_box(){
          //box데이터들 초기화 필요
            $('.row > div').each(function(index, item){
              $(item).attr('class', 'col');
              $(item).children('.user-status').text('');
              $(item).find('div.user-name').text('');
              $(item).find('div.user-rank').text('');
            });

          // 유저status

          for(var i = 0; i < eventsArray.length ; i++ ){
            eventInfo = eventsArray[i];

            var className;
            var status_kor;

            switch (eventInfo.status) {
              case 'place':
              case 'None':
                className = 'place-box';
                status_kor = '자리에 있음';
                break;
              case 'meeting':
                status_kor = '회의';
                className = 'empty-box';
                break;
              case 'away':
                status_kor = '자리비움';
                className = 'empty-box';
                break;
              case 'outside':
                status_kor = '외근';
                className = 'empty-box';
                break;
              default:
                className = 'place-box';
                status_kor = '자리에 있음';
                break;
            }


            console.log(eventInfo);
            //좌석 box 스타일 및 텍스트 업데이트
            if(eventInfo.seat_location !== 'None' && eventInfo.seat_location !== null){
                var location_to_id = '#' + eventInfo.seat_location;
                user_location_dom = $(location_to_id);
                user_location_dom.addClass(className);
                user_location_dom.children('.user-status').text(status_kor);
                user_location_dom.find('div.user-name').text(eventInfo.name);
                user_location_dom.find('div.user-rank').text(eventInfo.rank);
            }

            //좌석으로 돌아오기 버튼 업데이트

            if(eventInfo.user_id === '{{ current_user.userId }}' && eventInfo.seat_location !== null && eventInfo.seat_location !== 'None'){
                if(eventInfo.status !== 'place' && eventInfo.status !== null){
                    $('#place-button').css('display', 'block');
                    $('#return-button').text('자리로 돌아오기');
                }
                else{
                    $('#place-button').css('display', 'none');
                }

            }



          }

        }

        setInterval(function()
          {
            $.ajax({
              url         : '{{ url_for("dashboard_view.dashboard") }}'
               ,type        : 'POST'
               ,cache       : false
               ,contentType : 'application/json; charset=utf-8'
               ,dataType    : 'json'
               ,success     : function(data) {
                   eventsArray = [];
                   for(var i = 0; i < data.result.length ; i++){
                      eventsArray.push(data.result[i]);
                   }
                   update_user_box();
                }
               ,error: function(result) {
                 alert('통신에 오류가 발생했습니다. 자동으로 최신화 되지 못했습니다. 강제로 새로고침합니다.');
                 location.reload();
               }
            });
          },60000);


        //javascript에 객체 초기값 입력

        {% for event in events if events %}
        var eventInfo = new Object();
        eventInfo.id = '{{ event["id"] }}'
        eventInfo.user_id = '{{ event["user_id"] }}';
        eventInfo.rank = '{{ event["rank"] }}';
        eventInfo.status = '{{ event["status"] }}';
        eventInfo.name = '{{ event["name"] }}';
        eventInfo.seat_location = '{{ event["seat_location"] }}';
        eventInfo.category = '{{ event["category"] }}';
        eventInfo.place = '{{ event["place"] }}';
        eventInfo.subject = '{{ event["subject"] }}';
        eventInfo.start_time = '{{ event["start_time"] }}';
        eventInfo.attendants = '{{ event["attendants"] }}';
        eventInfo.attendants = eventInfo.attendants.replace('||', '<br>');

        eventsArray.push(eventInfo);
        {% endfor %}

        update_user_box();


        //별개
        var user_location = '';
        //dialog 생성
        infoDialog = document.querySelector('#info-dialog');
        infoDialogMDC = new MDCDialog(infoDialog);
        //추가하기 버튼
        addChannelButton = document.querySelector('.add_wrap > button');
        if(addChannelButton){
            addChannelButton.addEventListener('click',function(event){
                channel_id = prompt('등록을 원하는 채팅 채널 ID를 입력해주세요');
                if(channel_id.trim() !== ''){
                  register_url = '{{ url_for("register_channel_api.register_channel") }}' + '?channel=' + channel_id.trim();
                  location.href = register_url;
                }
                else{
                  alert('입력정보를 확인해주세요');
                }
            });
        }


        //완전 별개
        //그리드 클릭 이벤트
        $('.row > .col').on('click', function(){
            click_location = $(this).attr('id');
            click_status = $(this).find('div.user-status').text().trim();
            user_location = '{{ current_user.location }}';
            if(click_status != ''){
                //디테일 이벤트
                if(click_status == '자리에 있음'){
                    alert('자리에 잘 계십니다 ^^7');
                }
                else{
                    // 이벤트를 돌면서 해당 이벤트의 좌표와 클릭된 이벤의 좌표가 같을 경우 상태 출력
                    for(var index in eventsArray){
                        if(eventsArray[index].seat_location === click_location){
                            info_status = eventsArray[index].status == 'meeting' ? '회의'
                                : (eventsArray[index].status == 'away'? '자리비움' : '외근' )
                            info_name = eventsArray[index].name
                            info_place = eventsArray[index].place
                            info_subject = eventsArray[index].subject
                            info_start = eventsArray[index].start_time
                            info_attendants = eventsArray[index].attendants

                            //dialog title
                            $('#info-dialog-title').text(info_name + '님은 ' + info_status + ' 중 이십니다');

                            $('#info-content-wrap > div:nth-child(n)').css('display', 'block');

                            //dialog info
                            if(info_place == 'None'){
                                $('#info-content-wrap > div:nth-child(1)').css('display', 'none')
                            }
                            else{
                                $('#info-content-wrap > div:nth-child(1) .info-content').text(info_place);
                            }

                            if(info_subject == 'None'){
                                $('#info-content-wrap > div:nth-child(2)').css('display', 'none')
                            }
                            else{
                                $('#info-content-wrap > div:nth-child(2) .info-content').text(info_subject);
                            }

                            if(info_attendants == 'None'){
                                $('#info-content-wrap > div:nth-child(3)').css('display', 'none')
                            }
                            else{
                                $('#info-content-wrap > div:nth-child(3) .info-content').text(info_attendants);
                            }

                            if(info_start == 'None'){
                                $('#info-content-wrap > div:nth-child(4)').css('display', 'none')
                            }
                            else{
                                $('#info-content-wrap > div:nth-child(4) .info-content').text(info_start);
                            }


                            infoDialogMDC.open();
                        }
                    }
                }
            }
            else if(user_location === 'None'){
                var result = confirm('선택하신 좌표('+click_location+')를 자리로 하시겠습니까?')
                if(result){
                    location.href = '{{ url_for('user_api.update_location') }}' + '?location=' + click_location;
                }
            }
            else{
                var result = confirm('좌석을 ('+click_location+') 으로 이동 하시겠습니까?');
                if(result){
                    location.href = '{{ url_for('user_api.update_location') }}' + '?location=' + click_location;
                }
            }
        });

        //events, user 정보 읽어오기





    })
</script>
<div class="wrap">
    {% include "menu_sidebar.html" %}
    <div class="menu_body">
        {% include "menu_header.html" %}
        <div class="container">
        {% if current_user.channel %}
            <div id="seat-grid">
                {% for j in range(1,7) %}
                <div class="row">
                    {% for  i in range(1,11) %}
                    <div id="{{ j }}-{{ i }}" class="col">
                        <div class="user-status">
                        </div>
                        <div class="name-wrap">
                            <div class="user-name"></div>
                            <div class="user-rank"></div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="add_wrap">
                <div>채널을 등록해주세요</div>
                <button class="mdc-icon-button material-icons mdc-ripple-upgraded--unbounded mdc-ripple-upgraded" aria-label="Add to favorites" >add_circle_outline</button>
            </div>
        {% endif %}
        </div>
    </div>
</div>

<!--info dialog-->
<div id="info-dialog"
     class="mdc-dialog"
     role="alertdialog"
     aria-modal="true"
     aria-labelledby="my-dialog-title"
     aria-describedby="my-dialog-content">
  <div class="mdc-dialog__container">
    <div class="mdc-dialog__surface">
      <!-- Title cannot contain leading whitespace due to mdc-typography-baseline-top() -->
      <h2 class="mdc-dialog__title" id="info-dialog-title"><!--
     -->정보 조회<!--
   --></h2>
        <!--dialg 내용-->
      <div class="mdc-dialog__content" id="info-dialog-content">
        <div id="info-content-wrap">
            <div class="info-content-rows">
                <div class="info-tag">장소</div>
                <div class="info-content"></div>
            </div>
            <div class="info-content-rows">
                <div class="info-tag">주제</div>
                <div class="info-content"></div>
            </div>
            <div class="info-content-rows">
                <div class="info-tag">참석자</div>
                <div class="info-content"></div>
            </div>
            <div class="info-content-rows">
                <div class="info-tag">시작시간</div>
                <div class="info-content"></div>
            </div>
        </div>
      </div>
      <footer class="mdc-dialog__actions">
        <button type="button" class="mdc-button mdc-dialog__button" data-mdc-dialog-action="close">
          <span class="mdc-button__label">취소</span>
        </button>
      </footer>
    </div>
  </div>
  <div class="mdc-dialog__scrim"></div>
</div>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}echo_telegram{% endblock %}
{% block css %}
<style>
    .intro-container{
        background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url({{ url_for('static', filename='img/telegram.png') }});
        background-repeat: no-repeat;
        background-attachment: scroll;
        background-position: center center;
        background-size: cover;
        text-align: center;
        height: 700px;
        color: #fff;
    }
    .intro-lead-in{
        font-size: 40px;
        font-style: italic;
        line-height: 40px;
        margin-bottom: 25px;
        font-family: 'Droid Serif',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Noto Color Emoji';
    }
    .intro-text{
        padding: 250px 0px;
    }
    .intro-heading{
        font-size: 100px;
        font-weight: 700;
        line-height: 75px;
        margin-bottom: 50px;
        font-family: Montserrat,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Noto Color Emoji';
    }
    #start-button{

        background-color: rgb(40,160,294);
        font-size: 20px;
        font-weight: 700;
        width: 150px;
        height: 70px;
     }
     .first-container{
        text-align: center;
        margin-top: 70px;
     }
     #signup-button{
        --mdc-theme-primary
        color: rgb(40,160,294);
        border-color: rgb(40,160,294);
        font-size: 20px;
        font-weight: 700;
        width: 150px;
        height: 70px;
     }

</style>
{% endblock %}

{% block body %}

<div class="intro-container">
    <div class="intro-text">
        <div class="intro-lead-in">welcome!</div>
        <div class="intro-heading text-uppercase">Echo Telegram</div>
        <button id="start-button" class="mdc-button mdc-button--raised">시작하기</button>
    </div>
</div>
<div class="first-container">
    <h2>처음방문</h2>
    <button id="signup-button"class="mdc-button mdc-button--outlined">회원가입</button>
</div>

<div id="login-dialog"
     class="mdc-dialog"
     role="alertdialog"
     aria-modal="true"
     aria-labelledby="my-dialog-title"
     aria-describedby="my-dialog-content">
  <div class="mdc-dialog__container">
    <div class="mdc-dialog__surface">
      <!-- Title cannot contain leading whitespace due to mdc-typography-baseline-top() -->
      <h2 class="mdc-dialog__title" id="login-dialog-title"><!--
     -->로그인<!--
   --></h2>
        <!--dialg 내용-->
      <div class="mdc-dialog__content" id="login-dialog-content">
          <!--id_field-->
        <form method="post" action="{{ url_for('login_api.login') }}">
          <div class="mdc-text-field mdc-text-field--outlined">
              <input class="mdc-text-field__input" name="login_id">
              <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                  <label class="mdc-floating-label">ID</label>
                </div>
                <div class="mdc-notched-outline__trailing"></div>
              </div>
          </div>


          <div class="mdc-text-field mdc-text-field--outlined">
            <input class="mdc-text-field__input" type="password" name="login_pw">
            <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                    <label class="mdc-floating-label">PW</label>
                </div>
            <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
        </form>
      </div>
      <footer class="mdc-dialog__actions">
        <button type="button" class="mdc-button mdc-dialog__button" data-mdc-dialog-action="close">
          <span class="mdc-button__label">취소</span>
        </button>
        <button id="login-submit" type="button" class="mdc-button mdc-dialog__button">
          <span class="mdc-button__label">로그인</span>
        </button>
      </footer>
    </div>
  </div>
  <div class="mdc-dialog__scrim"></div>
</div>

<div id="signup-dialog"
     class="mdc-dialog"
     role="alertdialog"
     aria-modal="true"
     aria-labelledby="my-dialog-title"
     aria-describedby="my-dialog-content">
  <div class="mdc-dialog__container">
    <div class="mdc-dialog__surface">
      <!-- Title cannot contain leading whitespace due to mdc-typography-baseline-top() -->
      <h2 class="mdc-dialog__title" id="my-dialog-title"><!--
     -->회원가입<!--
   --></h2>
        <!--dialg 내용-->
      <div class="mdc-dialog__content" id="my-dialog-content">
          <!--id_field-->
        <form method="post" action="{{ url_for('signup_api.sign_up') }}">
          <div class="mdc-text-field mdc-text-field--outlined">
              <input class="mdc-text-field__input" name="signup_id">
              <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                  <label class="mdc-floating-label">ID</label>
                </div>
                <div class="mdc-notched-outline__trailing"></div>
              </div>
          </div>


          <div class="mdc-text-field mdc-text-field--outlined">
            <input class="mdc-text-field__input" type="password" name="signup_pw">
            <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                    <label class="mdc-floating-label">PW</label>
                </div>
            <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
          <div class="mdc-text-field mdc-text-field--outlined">
            <input class="mdc-text-field__input" type="password" name="signup_pw_check">
            <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                    <label class="mdc-floating-label">PW_CHECK</label>
                </div>
            <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
          <div class="mdc-text-field mdc-text-field--outlined">
            <input class="mdc-text-field__input" name="signup_name">
            <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                    <label class="mdc-floating-label">Name</label>
                </div>
            <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
          <!--Rank-->
          <div class="mdc-select demo-width-class mdc-select--outlined ">
              <input type="hidden" name="signup_rank">
              <i class="mdc-select__dropdown-icon"></i>

              <div id="demo-selected-text" class="mdc-select__selected-text" role="button" aria-haspopup="listbox" aria-labelledby="demo-label demo-selected-text">Vegetables</div>
              <div class="mdc-select__menu mdc-menu mdc-menu-surface demo-width-class" role="listbox">
                <ul class="mdc-list">
                  <li class="mdc-list-item mdc-list-item--selected" data-value="" role="option"></li>
                  <li class="mdc-list-item" data-value="실장" role="option">
                    실장
                  </li>
                  <li class="mdc-list-item" data-value="팀장" role="option">
                    팀장
                  </li>
                  <li class="mdc-list-item" data-value="부장" role="option">
                    부장
                  </li>
                  <li class="mdc-list-item" data-value="차장" role="option">
                    차장
                  </li>
                  <li class="mdc-list-item" data-value="과장" role="option">
                    과장
                  </li>
                  <li class="mdc-list-item" data-value="대리" role="option">
                    대리
                  </li>
                  <li class="mdc-list-item" data-value="사원" role="option">
                    사원
                  </li>
                </ul>
              </div>

              <div class="mdc-notched-outline">
                  <div class="mdc-notched-outline__leading"></div>
                  <div class="mdc-notched-outline__notch">
                      <label class="mdc-floating-label">Rank</label>
                  </div>
              <div class="mdc-notched-outline__trailing"></div>
              </div>
          </div>
        </form>
      </div>
      <footer class="mdc-dialog__actions">
        <button type="button" class="mdc-button mdc-dialog__button" data-mdc-dialog-action="close">
          <span class="mdc-button__label">취소</span>
        </button>
        <button id="sign-up-submit" type="button" class="mdc-button mdc-dialog__button">
          <span class="mdc-button__label">제출</span>
        </button>
      </footer>
    </div>
  </div>
  <div class="mdc-dialog__scrim"></div>
</div>

{% endblock %}

{% block script %}
<script>
 //flash 메시지 alert발생
    {% with lists = get_flashed_messages() %}
        {% for list in lists if lists%}
            alert('{{ list.decode("utf-8") }}');
        {% endfor %}
    {% endwith %}
$(function(){
    //회원가입 유효성검사 관련 변수 및 상수
    dupleCheck = false;
    pwCheck = false;
    korNamePattern = /^[가-힣]{2,5}$/;

    //회원가입 유효성 검사
    function signup_validation(){
        if(dupleCheck && pwCheck){
            //이름, 직급
            toCheck_name = $('#signup-dialog input[name="signup_name"]').val();
            toCheck_rank = $('#signup-dialog input[name="signup_rank"]').val();
            if(toCheck_name !== '' && korNamePattern.test(toCheck_name)){
                return true;
            }
            else{
                return false;
            }
        }
    }

    //login dialog설정
    loginDialog = document.querySelector('#login-dialog');
    loginDialogMDC = new MDCDialog(loginDialog);

    //signup dialog 설정
    signupDialog = document.querySelector('#signup-dialog');
    signupDialogMDC = new MDCDialog(signupDialog);


    //start button 설정
    startButton = document.querySelector('#start-button');
    startButtonRipple = new MDCRipple(startButton);
    startButton.addEventListener('click',function(event){
        {% if current_user.is_authenticated %}
            location.href = '{{ url_for("dashboard_view.dashboard") }}';
        {% else %}
            loginDialogMDC.open();
        {% endif %}
    });

    //login textfield 설정
    loginTextFields = [].map.call(document.querySelectorAll('#login-dialog .mdc-text-field'), function(el) {
      return new MDCTextField(el);
    });

    //login dialog 내부 요소들 이벤트 재설정
    loginDialogMDC.listen('MDCDialog:opened', () => {
        loginTextFields.forEach(function(element){
            element.layout();
        });
    });

    //login submit click
    $('#login-submit').on('click',function(event){
        toCheck_id = $('#login-dialog input[name="login_id"]').val();
        toCheck_pw = $('#login-dialog input[name="login_pw"]').val();
        if (toCheck_id !== '' && toCheck_pw !== ''){
            $('#login-dialog form').submit();
        }
        else{
            alert('입력정보를 다시 확인해주세요');
        }

    });

    //signup button 설정
    signupButton = document.querySelector('#signup-button');
    signupButtonRipple = new MDCRipple(signupButton);
    signupButton.addEventListener('click',function(event){
        signupDialogMDC.open();
    });

    //회원가입 textfield 설정
    signupTextFields = [].map.call(document.querySelectorAll('#signup-dialog .mdc-text-field'), function(el) {
      return new MDCTextField(el);
    });

    // 직급 selectbox 설정
    rankSelectMDC = new MDCSelect(document.querySelector('#signup-dialog .mdc-select'));
    rankSelectMDC.listen('MDCSelect:change', () => {

    });

    //signup dialog 내부 요소들 이벤트 재설정
    signupDialogMDC.listen('MDCDialog:opened', () => {
        signupTextFields.forEach(function(element){
            element.layout();
        });
        rankSelectMDC.layout();
    });

    $('#sign-up-submit').on('click',function(event){
        if (signup_validation()){
            $('#signup-dialog form').submit();
        }
        else{
            alert('입력정보를 다시 확인해주세요');
        }

    });

    $('#signup-dialog input[name="signup_id"]').on('focusout',function(){
        var toCheck_id =  $(this).val();
        if (toCheck_id != '') {
        $.ajax({
        	url         : '{{ url_for("signup_api.check_id") }}'
           ,type        : 'POST'
           ,cache       : false
           ,data        : JSON.stringify({
        	   user_id: toCheck_id
             })
           ,contentType : 'application/json; charset=utf-8'
           ,dataType    : 'json'
           ,success     : function(data) {
        	   user_id = toCheck_id
        	   if (data.result) {
                   dupleCheck = true;
        	   } else {
        	       dupleCheck = false;
        	       alert('이미 존재하는 ID입니다');
        	   }
             }
           ,error: function(result) {
        	   alert('통신에 오류가 발생했습니다. 잠시 후에 다시 사용하세요.');
               dupleCheck = false;
           }
        });

      } else {
    	  alert('사용자명을 넣어주세요.', function() {
              $(this).focus();
              dupleCheck = false;
    	  });
      }
    });

    //회원가입 비밀번호 확인 체크
     $('#signup-dialog input[name="signup_pw_check"]').on('focusout',function(){
        toCheck_pw_check = $(this).val();
        toCheck_pw = $('#signup-dialog input[name="signup_pw"]').val();
        if(toCheck_pw_check != '' && toCheck_pw != ''){
            pwCheck = toCheck_pw_check === toCheck_pw ? true : false;
        }
     });

})
</script>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="ko">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>

    <!--jquery-->
    <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>

    <!-- MATERIAL COMPONENTS -->
    <!--<link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/material-components-web.css') }}">
    <script src="{{ url_for('static', filename='js/material-components-web.js') }}"></script>
    <!--<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>-->

    <!--font-->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css">
    {% block head %}
    {% endblock %}
    <style>
    :root {
        --mdc-theme-primary: rgb(40,160,294);
        --mdc-theme-text-primary-on-background: rgb(40,160,294);
     }
    body{
        margin: 0;
    }
    .mdc-dialog .mdc-text-field,  .mdc-dialog .mdc-select{
        width: 486px;
        margin: 10px;
    }
    .demo-width-class{
        width: 486px;
    }

    </style>
    {% block css %}

    {% endblock %}
</head>
<script>
    //mdc event 관련 상수
    const MDCRipple = mdc.ripple.MDCRipple;
    const MDCDialog = mdc.dialog.MDCDialog;
    const MDCFormField = mdc.formField.MDCFormField;
    const MDCTextField = mdc.textField.MDCTextField;
    const MDCSelect = mdc.select.MDCSelect;
</script>
<body>
{% block body %}
{% endblock %}
<!--FOOTER START-->

<!--//FOOTER END-->

{% block script %}{% endblock %}
</body>
</html>